In [34]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import LabelEncoder


In [35]:
datos = pd.read_excel('./AirlineSatisfaction.xlsx')
datos.head(20)


id  Gender      Customer Type  Age   Type of Travel     Class  \
0    70172    Male     Loyal Customer   13  Personal Travel  Eco Plus   
1     5047    Male  disloyal Customer   25  Business travel  Business   
2   110028  Female     Loyal Customer   26  Business travel  Business   
3    24026  Female     Loyal Customer   25  Business travel  Business   
4   119299    Male     Loyal Customer   61  Business travel  Business   
5   111157  Female     Loyal Customer   26  Personal Travel       Eco   
6    82113    Male     Loyal Customer   47  Personal Travel       Eco   
7    96462  Female     Loyal Customer   52  Business travel  Business   
8    79485  Female     Loyal Customer   41  Business travel  Business   
9    65725    Male  disloyal Customer   20  Business travel       Eco   
10   34991  Female  disloyal Customer   24  Business travel       Eco   
11   51412  Female     Loyal Customer   12  Personal Travel  Eco Plus   
12   98628    Male     Loyal Customer   53  Business travel       Eco   
13   83502    Male     Loyal Customer   33  Personal Travel       Eco   
14   95789  Female     Loyal Customer   26  Personal Travel       Eco   
15  100580    Male  disloyal Customer   13  Business travel       Eco   
16   71142  Female     Loyal Customer   26  Business travel  Business   
17  127461    Male     Loyal Customer   41  Business travel  Business   
18   70354  Female     Loyal Customer   45  Business travel  Business   
19   66246    Male     Loyal Customer   38  Personal Travel       Eco   

    Flight Distance  Inflight wifi service  Departure/Arrival time convenient  \
0               460                      3                                  4   
1               235                      3                                  2   
2              1142                      2                                  2   
3               562                      2                                  5   
4               214                      3                                  3   
5              1180                      3                                  4   
6              1276                      2                                  4   
7              2035                      4                                  3   
8               853                      1                                  2   
9              1061                      3                                  3   
10             1182                      4                                  5   
11              308                      2                                  4   
12              834                      1                                  4   
13              946                      4                                  2   
14              453                      3                                  2   
15              486                      2                                  1   
16             2123                      3                                  3   
17             2075                      4                                  4   
18             2486                      4                                  4   
19              460                      2                                  3   

    Ease of Online booking  ...  Inflight entertainment  On-board service  \
0                        3  ...                       5                 4   
1                        3  ...                       1                 1   
2                        2  ...                       5                 4   
3                        5  ...                       2                 2   
4                        3  ...                       3                 3   
5                        2  ...                       1                 3   
6                        2  ...                       2                 3   
7                        4  ...                       5                 5   
8                        2  ...                       1                 1   
9 

In [36]:
datos.columns


Index(['id', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [37]:
datos.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5597 entries, 0 to 5596
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   id                                 5597 non-null   int64  
 1   Gender                             5597 non-null   object 
 2   Customer Type                      5597 non-null   object 
 3   Age                                5597 non-null   int64  
 4   Type of Travel                     5597 non-null   object 
 5   Class                              5597 non-null   object 
 6   Flight Distance                    5597 non-null   int64  
 7   Inflight wifi service              5597 non-null   int64  
 8   Departure/Arrival time convenient  5597 non-null   int64  
 9   Ease of Online booking             5597 non-null   int64  
 10  Gate location                      5597 non-null   int64  
 11  Food and drink                     5597 non-null   int64

In [38]:
Nulos = datos.isna().sum()
Nulos


id                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             16
satisfaction                          0
dtype: int64

In [39]:
datos['Arrival Delay in Minutes'].fillna(
    datos['Arrival Delay in Minutes'].mean(), inplace=True)


In [40]:
VarCat = []
for i in datos.columns:
    if datos[i].dtype == object:
        VarCat.append(i)
VarCat


['Gender', 'Customer Type', 'Type of Travel', 'Class', 'satisfaction']

In [41]:
for i in VarCat:
    print(datos[i].unique())


['Male' 'Female']
['Loyal Customer' 'disloyal Customer']
['Personal Travel' 'Business travel']
['Eco Plus' 'Business' 'Eco']
['neutral or dissatisfied' 'satisfied']


In [42]:
for y in VarCat:
    datos[y] = LabelEncoder().fit_transform(datos[y])

for i in VarCat:
    print(datos[i].unique())


[1 0]
[0 1]
[1 0]
[2 0 1]
[0 1]


In [43]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler

X = datos.drop(['id', 'satisfaction'], axis=1)
y = datos['satisfaction']

scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=101)

mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30), max_iter=300)
mlp.fit(X_train, y_train)

predictions = mlp.predict(X_test)

print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))
print(accuracy_score(y_test, predictions))


[[591  56]
 [ 27 446]]
              precision    recall  f1-score   support

           0       0.96      0.91      0.93       647
           1       0.89      0.94      0.91       473

    accuracy                           0.93      1120
   macro avg       0.92      0.93      0.92      1120
weighted avg       0.93      0.93      0.93      1120

0.9258928571428572


Precision = Por columnas, valor corroecto dividido entre la suma

Recall = Por filas, valor correcto dividido entre la suma

F1 = 2 * (precision * recall) / (precision + recall)

In [44]:
results = pd.DataFrame({'Actual': y_test, 'Predicted': predictions})
results

Actual  Predicted
1633       1          1
4546       0          0
2506       0          0
3131       0          0
3366       0          0
...      ...        ...
2867       0          0
1043       0          1
1180       0          0
2322       0          0
292        1          1

[1120 rows x 2 columns]

In [45]:
p = pd.DataFrame(datos['Flight Distance'])
z = pd.DataFrame(datos['Departure Delay in Minutes'])


In [62]:
z

Departure Delay in Minutes
0                             25
1                              1
2                              0
3                             11
4                              0
...                          ...
5592                           0
5593                           0
5594                           0
5595                          44
5596                           0

[5597 rows x 1 columns]

In [46]:
from sklearn.neural_network import MLPRegressor
RN3 = MLPRegressor(hidden_layer_sizes=(1), activation='identity', max_iter=500)
RN3.fit(z, p)


c:\Users\Jorge\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1607: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Jorge\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(activation='identity', hidden_layer_sizes=1, max_iter=500)

In [47]:
pred = RN3.predict(z)
pred

array([405.0016649 , 142.87505722, 131.95311523, ..., 131.95311523,
       612.51856264, 131.95311523])

In [48]:
from sklearn.metrics import mean_squared_error

In [49]:
mean_squared_error(p, pred)

1995848.4617615144

In [50]:
np.sqrt(mean_squared_error(p, pred))

1412.7450094626115

In [51]:
RN3.coefs_ #pesos

[array([[-1.32321401]]), array([[-8.25410094]])]

In [52]:
RN3.intercepts_ #bias

[array([-14.34450582]), array([13.55211624])]

In [57]:
pred


array([405.0016649 , 142.87505722, 131.95311523, ..., 131.95311523,
       612.51856264, 131.95311523])

In [61]:
p

Flight Distance
0                 460
1                 235
2                1142
3                 562
4                 214
...               ...
5592             2934
5593              677
5594              455
5595              746
5596              125

[5597 rows x 1 columns]

In [63]:
x3=datos.drop(['id','Flight Distance'], axis=1)

In [64]:
y3=datos['Flight Distance']

In [65]:
x3.shape

(5597, 22)

In [71]:
RN3 = MLPRegressor(hidden_layer_sizes=(1), activation='identity', max_iter=500)
RN3.fit(x3, y3)

c:\Users\Jorge\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(activation='identity', hidden_layer_sizes=1, max_iter=500)

In [73]:
pred_reg = RN3.predict(x3)
pred_reg

array([1065.99439729,  809.10309137, 1442.53135266, ..., 1169.13694448,
       1437.29186225, 1180.55590891])

In [74]:
mean_squared_error(y3, pred_reg)

903551.1449431524

In [75]:
np.sqrt(mean_squared_error(y3, pred_reg))

950.5530731858966

In [77]:
print('VAMOS A SUMAR!!!!!!!!!!!!!!!!!')
a = input('Introduce un numero')
b = input('Introduce otro numero')
print('La suma de '+str(a)+' + '+str(b)+' = '+str(a)+str(b))


VAMOS A SUMAR!!!!!!!!!!!!!!!!!
La suma de 2 + 3 = 23
